[iOS] 옵셔널이란?
ThinLineIT/CtrlF_Data pull request #111
Opened 2021-07-28 20:36 UTC by comeheredart

오랜만입니다 ㅎㅎ

2021-08-22 11:26 UTC, syg4806 requested changes

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +
코드는 코드블락으로 감싸주세요
`var name: String?`

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +    ar name = nil // 컴파일에러
[ditto] 멀티라인의 경우에는 요런식으로 해주시면 더 좋습니다.
\```swift
    var name: String // 컴파일에러
    var name = nil // 컴파일에러
\```

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +    number1 + number2
[ditto]

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +Value of optional type 'Int?' not unwrapped; did you mean to use '!' or '?'?
[ditto] \`Value of optional type 'Int?' not unwrapped; did you mean to use '!' or '?'?`

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +    }
[ditto]

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +    }
[ditto]

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +    }
[ditto]

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +    }
[ditto]

2021-08-22 11:26 UTC, syg4806 commented on iOS/what's Optional.md
> +    ar name = nil // 컴파일에러
`ar` 이 아니라 `var`을 의도하신가죠?

2021-08-24 11:03 UTC, comeheredart commented on iOS/what's Optional.md
> +    ar name = nil // 컴파일에러
이런게있었군ㄴ요!!

2021-08-24 11:04 UTC, comeheredart commented on iOS/what's Optional.md
> +Value of optional type 'Int?' not unwrapped; did you mean to use '!' or '?'?
이런것도 있었군요!!!!

2021-08-24 11:06 UTC, comeheredart commented
고쳤습니다!

2021-09-24 15:44 UTC, merged