Algorithm/MergeSort
ThinLineIT/CtrlF_Data pull request #12
Opened 2021-05-08 09:04 UTC by myeongheonhong

MergeSort Definition Code example, Time Complexity

2021-05-10 13:01 UTC, syg4806 requested changes

2021-05-10 13:01 UTC, syg4806 commented on Algorithm/MergeSort.md
> +    + 정렬이 안정적이다.
정렬이 안정적이다라는게 무슨말일까요?

2021-06-23 13:20 UTC, syg4806 requested changes

2021-06-23 13:20 UTC, syg4806 commented on Algorithm/MergeSort.md
> +    + 정렬이 안정적이다.(무조건 절반으로 나눠서 정렬을 진행 하기 때문에 Quick Sort 처럼 pivot에 따라 성능이 안좋아지거나 하는 경우가 없다.)
https://blog.naver.com/zephyehu/150013176075
안정적이다는 것은 stable 하다는 것인데, 해당 내용을 보고 다시한번 정리해보세요

2021-06-25 07:39 UTC, myeongheonhong commented on Algorithm/MergeSort.md
> +    + 정렬이 안정적이다.(무조건 절반으로 나눠서 정렬을 진행 하기 때문에 Quick Sort 처럼 pivot에 따라 성능이 안좋아지거나 하는 경우가 없다.)
네! 잘 읽어봤습니다!! 그런데 제가 의도했던 장점은 안정적인 성능이라 다시 문장 수정했습니다!! 혹시나 안정적인 정렬도 장점에 해당되어 추가하게 된다면 정리해서 추가하겠습니다!

2021-06-29 01:38 UTC, syg4806 commented on Algorithm/MergeSort.md
> +    + 정렬이 안정적이다.(무조건 절반으로 나눠서 정렬을 진행 하기 때문에 Quick Sort 처럼 pivot에 따라 성능이 안좋아지거나 하는 경우가 없다.)
넵 stable도 머지소트 장점입니다!

2021-06-29 01:39 UTC, syg4806 commented on Algorithm/MergeSort.md
> +    + 정렬이 안정적이다.(무조건 절반으로 나눠서 정렬을 진행 하기 때문에 Quick Sort 처럼 pivot에 따라 성능이 안좋아지거나 하는 경우가 없다.)
내용추가부탁드려요

2021-07-07 13:49 UTC, merged