Observable2
ThinLineIT/CtrlF_Data pull request #24
Opened 2021-05-26 12:12 UTC by comeheredart

2021-05-30 14:36 UTC, syg4806 requested changes
설명은 자세하게 잘 되어 있는데 마크다운 문법이나 주석이 이해안가는 부분이 있습니다..!

2021-05-30 14:36 UTC, syg4806 commented on iOS/Observable 2.md
> +## 4. Observable 구독하기
아마 <br/>직후에 ##이 적용안되는 듯 하네요

2021-05-30 14:36 UTC, syg4806 commented on iOS/Observable 2.md
> +// 여기 직접 실행해보기<br/><br/>
요 주석은 의도하신건가요?

2021-05-30 14:36 UTC, syg4806 commented on iOS/Observable 2.md
> +// 여기도 직접 실행해보기
dito

2021-05-30 14:36 UTC, syg4806 commented on iOS/Observable 2.md
> +- 아무것도 출력되지 않는다. Completed 도 안나온다.<br/><br/>
never는 그럼 언제사용하죠??

2021-05-30 14:36 UTC, syg4806 commented on iOS/Observable 2.md
> +<br/><br/>
필요한가요??

2021-05-30 14:36 UTC, syg4806 commented on iOS/Observable 2.md
> +다음과 같이 사용하기! //사실 다 까먹을 거 같음 ;;ㅎ
네..?

2021-05-30 18:35 UTC, comeheredart commented on iOS/Observable 2.md
> +// 여기 직접 실행해보기<br/><br/>
의도한건데 비공식적이니 삭제하겠습니다!

2021-05-30 18:37 UTC, comeheredart commented on iOS/Observable 2.md
> +- 아무것도 출력되지 않는다. Completed 도 안나온다.<br/><br/>
empty 는 item 을 emit하지 않으나 종료하지만, never 는 종료하지 않습니다! 주로 production에 쓰이지 않고 테스팅에 쓰인다고합니다,,

2021-05-30 18:37 UTC, comeheredart commented on iOS/Observable 2.md
> +다음과 같이 사용하기! //사실 다 까먹을 거 같음 ;;ㅎ
까먹을거같긴합니다 ㅎㅋㅎㅋ

2021-05-31 05:32 UTC, syg4806 requested changes

2021-05-31 05:32 UTC, syg4806 commented on iOS/Observable 2.md
> +- 아무것도 출력되지 않는다. Completed 도 안나온다.<br/><br/>
그 내용을 적어주시면 좋을 것 같아요

2021-05-31 05:32 UTC, syg4806 commented on iOS/Observable 2.md
> +											print($0) }
왜 print 왕따시켜요

2021-06-08 13:09 UTC, syg4806 approved these changes

2021-06-08 16:44 UTC, merged