Dynamic Programming.md
ThinLineIT/CtrlF_Data pull request #34
Opened 2021-06-18 08:13 UTC by toy9910

2021-06-20 15:22 UTC, syg4806 requested changes
전반적으로 마크다운 문법 커밋전에 Preview로 확인해보시길 바라요.

2021-06-20 15:22 UTC, syg4806 commented on Algorithm/Dynamic Programming.md
> +#동적 계획법(Dynamic Programming)
`#`뒤에 공백하나 있어야 해요

2021-06-20 15:22 UTC, syg4806 commented on Algorithm/Dynamic Programming.md
> +#동적 계획법(Dynamic Programming)
아래도 모두 확인바랍니다

2021-06-20 15:22 UTC, syg4806 commented on Algorithm/Dynamic Programming.md
> +##분할 정복과의 차이점
분할 정복도 영어 명칭 적어주면 좋을 것 같아요

2021-06-21 15:21 UTC, syg4806 requested changes

2021-06-21 15:21 UTC, syg4806 commented on Algorithm/Dynamic Programming.md
> +##Reference
ㅎㅎ Preview 꼼꼼히 확인부탁해요

2021-06-21 15:22 UTC, syg4806 commented
Reference쪽 수정하고 머지해주세요

2021-06-22 05:52 UTC, toy9910 commented on Algorithm/Dynamic Programming.md
> +##Reference
알겠습니다..!!

2021-06-22 05:59 UTC, merged