Algorithm/BFS
ThinLineIT/CtrlF_Data pull request #36
Opened 2021-06-22 10:00 UTC by toy9910

2021-06-22 10:09 UTC, syg4806 requested changes

2021-06-22 10:09 UTC, syg4806 commented on Algorithm/BFS.md
> +  - 노드의 수가 늘어나면 탐색해야하는 노드 또한 많아지기에 비현실적이다.
알고리즘의 장단점을 비교할 때는 시간복잡도와 공간복잡도를 함께 정리해주면 좋을 듯합니다

2021-06-23 13:16 UTC, syg4806 requested changes

2021-06-23 13:16 UTC, syg4806 commented on Algorithm/BFS.md
> +    - 정점의 개수가 n이고 최고 깊이가 d인 그래프에서의 공간복잡도는 O(b^d)이다.
공간복잡도는 Big O 로 표현하지않습니다!

2021-06-24 02:29 UTC, toy9910 commented on Algorithm/BFS.md
> +    - 정점의 개수가 n이고 최고 깊이가 d인 그래프에서의 공간복잡도는 O(b^d)이다.
![image](https://user-images.githubusercontent.com/50603217/123192948-d9fd0c80-d4de-11eb-90cc-b07e17fa2a97.png)
제가 조사한 자료에서는 빅오 표기법으로 표기했는데 혹시 공간복잡도를 표현할 때 사용하는 표기법이 따로 있을까요..?ㅠㅠ

2021-06-29 01:42 UTC, syg4806 commented on Algorithm/BFS.md
> +    - 정점의 개수가 n이고 최고 깊이가 d인 그래프에서의 공간복잡도는 O(b^d)이다.
앗 죄송합니다. S로 표현하는 줄 알았는데 다시 찾아보니 공간복잡도도 Big O를 이용하는군요 ㅎㅎ..

2021-06-29 01:42 UTC, merged