Android/recyclerview VS listview
ThinLineIT/CtrlF_Data pull request #39
Opened 2021-06-22 15:36 UTC by leejungmin05

2021-06-23 13:26 UTC, syg4806 commented
PR명, 중복된 파일이 있습니다 확인해주세요!

2021-06-23 13:28 UTC, syg4806 requested changes

2021-06-23 13:28 UTC, syg4806 commented on Android/listview.md
> +   *그러나, listView는 사실상 deprecated 되었음.*
listview는 현재 안드로이드 내에서도 legacy로 분류되기 때문에 사실상 deprecated 되었다고 볼 수 있다.
따라서, RecyclerView를 사용 하도록 노력하자!

2021-06-27 04:52 UTC, leejungmin05 commented
중복된 파일 어떻게 지우나요 ...? ㅠㅠ

2021-06-29 01:57 UTC, syg4806 commented
각 브랜치에서 제거하면 될 듯합니다

2021-07-06 09:00 UTC, closed without merging