Android/Activity-lifecycle
ThinLineIT/CtrlF_Data pull request #6
Opened 2021-05-03 09:39 UTC by leejungmin05

activity life cycle

2021-05-03 12:48 UTC, syg4806 requested changes
State 내용만 추가해주세용

2021-05-03 12:48 UTC, syg4806 commented on Android/Activity Life Cycle.md
> +
activity 의 상태를 표현하는 표도 있는데 해당 표도 추가해주세요!
created, started, destroyed 뭐 이런거였던 것 같아요..

2021-05-03 12:48 UTC, syg4806 commented on Android/Activity Life Cycle.md
> +
<img width="530" alt="스크린샷 2021-05-03 오후 9 48 19" src="https://user-images.githubusercontent.com/56154295/116877733-47b45700-ac59-11eb-8aea-092d58964af8.png">
이런 표인데 공식문서에있을거에요

2021-05-05 15:27 UTC, leejungmin05 commented on Android/Activity Life Cycle.md
> +
핑프 아니고 공식문서에 26시간 49분 10초 동안 찾았는데 못찾겠어요 .. ㅠㅠ

2021-05-06 11:39 UTC, leejungmin05 commented on Android/Activity Life Cycle.md
> +
헉 찾앗다

2021-05-06 11:42 UTC, leejungmin05 commented on Android/Activity Life Cycle.md
> +
![라이프사이클](https://developer.android.com/images/topic/libraries/architecture/lifecycle-states.svg)
이거맞나요

2021-05-07 20:14 UTC, syg4806 commented on Android/Activity Life Cycle.md
> +
멋져 당신

2021-05-07 20:15 UTC, syg4806 approved these changes
저 상태가 매우 중요하니 꼭 숙지 해두시면 좋을 것 같아요! 수고하셨습니다!

2021-05-09 06:06 UTC, merged