composing suspending function.md
ThinLineIT/CtrlF_Data pull request #69
Opened 2021-07-06 14:51 UTC by leejungmin05

2021-07-11 16:14 UTC, syg4806 approved these changes
각 예시 코드의 실행결과도 함께 첨부해주세요

2021-07-11 16:14 UTC, syg4806 commented on Android/Composing suspending func.md
> +deferred value는 await()를 만나서 결과를 얻을 수 있음.
만나서 -> 이용해

2021-07-11 16:14 UTC, syg4806 commented on Android/Composing suspending func.md
> +코틀린 코루틴과 함께 이 스타일을 사용하는 것은 아래에 설명된 이유 때문에 강력히 권장되지 않습니다.
"이 스타일 " 이 정확히 무엇인지 가늠하기 힘드네요
-> "매번 Global Scope를 만들어서 각자의 코루틴에서 작동하게끔 사용하는 스타일은"

2021-07-11 16:15 UTC, syg4806 requested changes
Request changes

2021-07-11 17:22 UTC, syg4806 commented
> 각 예시 코드의 실행결과도 함께 첨부해주세요

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2021-07-12 14:59 UTC, leejungmin05 commented
죄송합니다 추가했습니다 하핫,,,

2021-07-13 15:27 UTC, syg4806 approved these changes

2021-07-13 15:27 UTC, merged