KMP.md
ThinLineIT/CtrlF_Data pull request #89
Opened 2021-07-17 09:11 UTC by toy9910

2021-07-21 07:54 UTC, syg4806 requested changes
정리 열심히 해주셨는데,, 과정부분에 있는 스트링이랑 구현 부분에 있느 스트링이 달라서 이해가 힘드네요. 구현 부분에 예시가 이해하기 좋지 않은 것 같아요.
Search문자열이 "ABDABB" 여야지  AB부터 다시 검사하는게 와닿을 텐데, "ABADAB'로 검색하니 AB부터 다시 검색하는 케이스가 나오지 않네요... 내용은 좋은데, 이해하기가 다소 난해합니다. 한번 다시 정리 해보시겠어요?

2021-07-21 08:40 UTC, toy9910 commented
그럼 과정 부분의 문자열을 구현 부분과 통일하면 괜찮을까요?

2021-07-21 13:24 UTC, syg4806 commented
제 생각엔 구현부분이 과정과 같아져야할것같아요..
많이 내용이 바뀌긴 하겠지만, 과정 부분의 문자열이 케이스 이해하기 더 좋은 문자열인 것 같아요

2021-07-24 01:53 UTC, toy9910 commented
수정했습니다! 확인부탁드려요!

2021-07-25 08:48 UTC, merged